import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import ReactQueryProvider from "@/Components/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Posts CRUID App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-[100dvh] w-[100dvw] bg-slate-200 dark:bg-[#151d35]`}
      >
        <ReactQueryProvider>
          <div className="w-full h-full p-2 flex flex-col gap-2">
            <Navbar />
            {children}
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
